# Algortihm Parameters
nepisodes: 5
nsteps: 50

# Environment Parameters
drone1:
    max_altitude: 2.0   # in meters
    max_incl: 0.7       # in rads
    speed_value: 0.3   # in m/s
    running_step: 0.3   # in seconds

goal:
    desired_pose:
        x: 5
        y: 5
        z: 5