# Environment Parameters
drone1:
    max_altitude: 2.0   # in meters
    max_incl: 0.7       # in rads
    speed_value: 0.3   # in m/s
    running_step: 0.3   # in seconds

goal:
    desired_pose:
        x: 5
        y: 5
        z: 5

# Reset positions
reset_positions:
    cf1:
        x: 0.5
        y: 0.0
        z: 2.0
    # cf2:
    #     x: -0.5
    #     y: 0.0
    #     z: 2.0
    # cf3:
    #     x: 0.0
    #     y: 0.5
    #     z: 2.0
    # cf4:
    #     x: 0.0
    #     y: -0.5
    #     z: 2.0
