# Algortihm Parameters
nepisodes: 5
nsteps: 50

# Environment Parameters
drone1:
    desired_pose:
        x: 5
        y: 1
        z: 1
    max_altitude: 2.0   # in meters
    max_incl: 0.7       # in rads
    speed_value: 0.3   # in m/s
    running_step: 0.3   # in seconds

drone2:
    desired_pose:
        x: 5
        y: 0
        z: 1
    max_altitude: 2.0   # in meters
    max_incl: 0.7       # in rads
    speed_value: 0.3    # in m/s
    running_step: 0.3   # in seconds

drone3:
    desired_pose:
        x: 5
        y: -1
        z: 1
    max_altitude: 2.0   # in meters
    max_incl: 0.7       # in rads
    speed_value: 0.3  # in m/s
    running_step: 0.3   # in seconds



